export const FETCH_LEASES_START = 'FETCH_LEASES_START';
export const FETCH_LEASES_SUCCESS = 'FETCH_LEASES_SUCCESS';
export const FETCH_LEASES_FAIL = 'FETCH_LEASES_FAIL';

export const FETCH_LEASE_START = 'FETCH_LEASE_START';
export const FETCH_LEASE_SUCCESS = 'FETCH_LEASE_SUCCESS';
export const FETCH_LEASE_FAIL = 'FETCH_LEASE_FAIL';